// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/G-Villarinho/food-shop-api/client"

	mock "github.com/stretchr/testify/mock"
)

// MailtrapClient is an autogenerated mock type for the MailtrapClient type
type MailtrapClient struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: ctx, payload
func (_m *MailtrapClient) SendEmail(ctx context.Context, payload client.MailtrapPayload) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.MailtrapPayload) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMailtrapClient creates a new instance of MailtrapClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailtrapClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailtrapClient {
	mock := &MailtrapClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
