// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// ProductHandler is an autogenerated mock type for the ProductHandler type
type ProductHandler struct {
	mock.Mock
}

// GetPopularProducts provides a mock function with given fields: ctx
func (_m *ProductHandler) GetPopularProducts(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPopularProducts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductHandler creates a new instance of ProductHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductHandler {
	mock := &ProductHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
