// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// RestaurantHandler is an autogenerated mock type for the RestaurantHandler type
type RestaurantHandler struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx
func (_m *RestaurantHandler) CreateOrder(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRestaurant provides a mock function with given fields: ctx
func (_m *RestaurantHandler) CreateRestaurant(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateRestaurant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRestaurantHandler creates a new instance of RestaurantHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRestaurantHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *RestaurantHandler {
	mock := &RestaurantHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
